name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
      - name: Get changed files using defaults
        id: changed-files
        uses: tj-actions/changed-files@v29.0.2
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: List all added files
        run: for file in ${{ steps.changed-files.outputs.added_files }}; |
          do
            echo "$file was added"
          done